version: '3.8'
services:
  openvpn-server:
    build:
      dockerfile: Dockerfile
      context: .
    privileged: true
    environment:
      - OPENVPN_CONFIG_FILE=/etc/openvpn/server.conf
      - NAT_MASQUERADE=1
      - CUSTOM_FIREWALL_SCRIPT=/etc/openvpn/firewall.sh
    volumes:
      - ./openvpn/server.conf:/etc/openvpn/server.conf
      - ./openvpn/firewall.sh:/etc/openvpn/firewall.sh
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 1194:1194/udp
      - 5001:5001  # Porta 5001 mapeada para o VPS (não mudada)
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.forwarding=1
    devices:
     - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

  openvpn-client:
    build:
      dockerfile: Dockerfile
      context: .
    privileged: true
    environment:
      - OPENVPN_CONFIG_FILE=/etc/openvpn/client.conf
      - NAT_MASQUERADE=0
      - CUSTOM_FIREWALL_SCRIPT=/etc/openvpn/firewall.sh
    volumes:
      - ./openvpn/client.conf:/etc/openvpn/client.conf
      - ./openvpn/firewall.sh:/etc/openvpn/firewall.sh
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.forwarding=1
    restart: unless-stopped